# Generated by Django 4.2.6 on 2023-10-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_uploadedfile_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.TextField(default='name'),
        ),
    ]
